name: Linux Compatibility Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-version: ['6.0']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift ${{ matrix.swift-version }}
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
      continue-on-error: true
      id: swift-setup
    
    - name: Manual Swift installation (fallback)
      if: steps.swift-setup.outcome == 'failure'
      run: |
        echo "Swift setup failed, attempting manual installation..."
        
        # Download Swift
        wget -q https://download.swift.org/swift-6.0.3-release/ubuntu2004/swift-6.0.3-RELEASE-ubuntu20.04.tar.gz
        
        # Extract Swift
        tar xzf swift-6.0.3-RELEASE-ubuntu20.04.tar.gz
        
        # Add to PATH
        echo "$PWD/swift-6.0.3-RELEASE-ubuntu20.04/usr/bin" >> $GITHUB_PATH
        
        # Verify installation
        $PWD/swift-6.0.3-RELEASE-ubuntu20.04/usr/bin/swift --version
    
    - name: Verify Swift installation
      run: |
        swift --version
        which swift
    
    - name: Cache Swift packages
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/.cache/org.swift.swiftpm
        key: ${{ runner.os }}-swift-${{ matrix.swift-version }}-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-${{ matrix.swift-version }}-
          ${{ runner.os }}-swift-
    
    - name: Build project
      run: swift build --verbose
    
    - name: Run tests
      run: swift test --verbose
    
    - name: Build demo project
      run: |
        cd Demo
        swift build --verbose
    
    - name: Test demo execution
      run: |
        cd Demo
        swift run Objects2XLSXDemo -s small -v /tmp/demo_test.xlsx
        ls -la /tmp/demo_test.xlsx