name: Linux Compatibility Tests

on:
  push:
    branches: [ main, develop, fix-linux-trailing-comma ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-linux:
    name: Test on Linux
    runs-on: ubuntu-latest
    container:
      image: swift:6.0
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Verify Swift installation
      run: |
        swift --version
        which swift
    
    - name: Cache Swift packages
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/.cache/org.swift.swiftpm
        key: ${{ runner.os }}-swift-6.0-${{ github.sha }}
        restore-keys: |
          ${{ runner.os }}-swift-6.0-
          ${{ runner.os }}-swift-
    
    - name: Build project
      run: swift build --verbose
    
    - name: Run tests
      run: swift test --verbose
    
    - name: Build demo project
      run: |
        cd Demo
        swift build --verbose
    
    - name: Test demo execution
      run: |
        cd Demo
        swift run Objects2XLSXDemo -s small -v /tmp/demo_test.xlsx
        ls -la /tmp/demo_test.xlsx