name: Linux Compatibility Tests

on:
  push:
    branches: [ main, develop ]
  pull_request:
    branches: [ main, develop ]

jobs:
  test-linux:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        swift-version: ['6.0']
    
    steps:
    - name: Checkout code
      uses: actions/checkout@v4
    
    - name: Setup Swift ${{ matrix.swift-version }}
      uses: swift-actions/setup-swift@v2
      with:
        swift-version: ${{ matrix.swift-version }}
      continue-on-error: true
      id: swift-setup
    
    - name: Install Swift using Swiftly (fallback)
      if: steps.swift-setup.outcome == 'failure'
      run: |
        echo "Swift setup failed, installing Swift using Swiftly..."
        
        # Install Swiftly with non-interactive setup
        echo "1" | curl -L https://swiftlang.github.io/swiftly/swiftly-install.sh | bash
        
        # Add Swiftly to PATH for current session
        export PATH="$HOME/.local/bin:$PATH"
        
        # Install Swift 6.0 using Swiftly with Ubuntu 22.04 platform
        echo "Installing Swift 6.0 using Swiftly..."
        $HOME/.local/bin/swiftly install 6.0 --platform ubuntu2204
        
        # Use Swift 6.0
        $HOME/.local/bin/swiftly use 6.0
        
        # Add Swift to PATH permanently
        echo "$HOME/.local/share/swiftly/toolchains/6.0/usr/bin" >> $GITHUB_PATH
        
        # Verify installation
        $HOME/.local/share/swiftly/toolchains/6.0/usr/bin/swift --version
    
    - name: Verify Swift installation
      run: |
        swift --version
        which swift
    
    - name: Cache Swift packages
      uses: actions/cache@v4
      with:
        path: |
          .build
          ~/.cache/org.swift.swiftpm
        key: ${{ runner.os }}-swift-${{ matrix.swift-version }}-${{ hashFiles('**/Package.resolved') }}
        restore-keys: |
          ${{ runner.os }}-swift-${{ matrix.swift-version }}-
          ${{ runner.os }}-swift-
    
    - name: Build project
      run: swift build --verbose
    
    - name: Run tests
      run: swift test --verbose
    
    - name: Build demo project
      run: |
        cd Demo
        swift build --verbose
    
    - name: Test demo execution
      run: |
        cd Demo
        swift run Objects2XLSXDemo -s small -v /tmp/demo_test.xlsx
        ls -la /tmp/demo_test.xlsx